2021-03-10 18:35:30,501 INFO    Thread-20 :3616 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'dl_assignment1', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': '00phcm50', 'run_id': 'ezc0wpid', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-00phcm50\\config-ezc0wpid.yaml'}
2021-03-10 18:35:30,501 INFO    Thread-20 :3616 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-10 18:35:30,502 INFO    Thread-20 :3616 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210310_183530-ezc0wpid\logs\debug.log
2021-03-10 18:35:30,503 INFO    Thread-20 :3616 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210310_183530-ezc0wpid\logs\debug-internal.log
2021-03-10 18:35:30,505 INFO    Thread-20 :3616 [wandb_init.py:init():352] calling init triggers
2021-03-10 18:35:30,505 INFO    Thread-20 :3616 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0, 'batch_size': 16, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'xavier', 'learning_rate': 0.001, 'loss_func': 'crossentropy', 'n_hidden_layers': 4, 'optimizer': 'nadam', 'size_hidden_layers': 64}
config: {}
2021-03-10 18:35:30,506 INFO    Thread-20 :3616 [wandb_init.py:init():398] wandb.init() called when a run is still active
2021-03-10 18:37:14,636 ERROR   Thread-13 :3616 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-10 18:37:14,636 ERROR   Thread-13 :3616 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-10 18:37:59,807 ERROR   Thread-13 :3616 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-10 18:37:59,807 ERROR   Thread-13 :3616 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-10 18:38:44,830 ERROR   Thread-13 :3616 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-10 18:38:44,831 ERROR   Thread-13 :3616 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-10 18:41:57,540 INFO    Thread-20 :3616 [wandb_run.py:finish():1078] finishing run -my/dl_assignment1/ezc0wpid
2021-03-10 18:41:57,541 INFO    Thread-20 :3616 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 1
2021-03-10 18:41:57,542 INFO    Thread-20 :3616 [wandb_run.py:_restore():1364] restore
2021-03-10 18:41:58,257 INFO    Thread-20 :3616 [wandb_run.py:_wait_for_finish():1515] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 787
  total_bytes: 787
}

2021-03-10 18:42:00,267 INFO    Thread-20 :3616 [wandb_run.py:_wait_for_finish():1515] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3708
  total_bytes: 3708
}

2021-03-10 18:42:02,236 INFO    Thread-20 :3616 [wandb_run.py:_show_files():1737] logging synced files
2021-03-10 18:42:02,246 ERROR   MainThread:3616 [pyagent.py:_run_jobs_from_queue():231] Run ezc0wpid errored: TypeError("unhashable type: 'numpy.ndarray'",)
2021-03-10 18:42:06,034 INFO    Thread-26 :3616 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'dl_assignment1', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': '00phcm50', 'run_id': 'tncnr4za', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-00phcm50\\config-tncnr4za.yaml'}
2021-03-10 18:42:06,036 INFO    Thread-26 :3616 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-10 18:42:06,037 INFO    Thread-26 :3616 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210310_184205-tncnr4za\logs\debug.log
2021-03-10 18:42:06,040 INFO    Thread-26 :3616 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210310_184205-tncnr4za\logs\debug-internal.log
2021-03-10 18:42:06,041 INFO    Thread-26 :3616 [wandb_init.py:init():352] calling init triggers
2021-03-10 18:42:06,042 INFO    Thread-26 :3616 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0, 'batch_size': 16, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'xavier', 'learning_rate': 0.001, 'loss_func': 'crossentropy', 'n_hidden_layers': 4, 'optimizer': 'nadam', 'size_hidden_layers': 64}
config: {'batch_size': 64, 'learning_rate': 0.001, 'epochs': 10, 'n_hidden_layers': 4, 'size_hidden_layers': 64, 'optimizer': 'adam'}
2021-03-10 18:42:06,044 INFO    Thread-26 :3616 [wandb_init.py:init():401] starting backend
2021-03-10 18:42:06,045 INFO    Thread-26 :3616 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-10 18:42:06,066 INFO    Thread-26 :3616 [backend.py:ensure_launched():123] starting backend process...
2021-03-10 18:42:07,231 INFO    Thread-26 :3616 [backend.py:ensure_launched():128] started backend process with pid: 14120
2021-03-10 18:42:07,235 INFO    Thread-26 :3616 [wandb_init.py:init():406] backend started and connected
2021-03-10 18:42:07,248 INFO    Thread-26 :3616 [wandb_run.py:_config_callback():669] config_cb None None {'alpha': 0, 'batch_size': 16, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'xavier', 'learning_rate': 0.001, 'loss_func': 'crossentropy', 'n_hidden_layers': 4, 'optimizer': 'nadam', 'size_hidden_layers': 64}
2021-03-10 18:42:07,251 INFO    Thread-26 :3616 [wandb_init.py:init():446] updated telemetry
2021-03-10 18:42:07,255 INFO    Thread-26 :3616 [wandb_init.py:init():465] communicating current version
2021-03-10 18:42:10,315 INFO    Thread-26 :3616 [wandb_init.py:init():470] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-10 18:42:10,319 INFO    Thread-26 :3616 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2021-03-10 18:42:11,047 INFO    Thread-26 :3616 [wandb_init.py:init():503] starting run threads in backend
2021-03-10 18:42:16,185 INFO    Thread-26 :3616 [wandb_run.py:_console_start():1422] atexit reg
2021-03-10 18:42:16,197 INFO    Thread-26 :3616 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.WRAP
2021-03-10 18:42:16,200 INFO    Thread-26 :3616 [wandb_run.py:_redirect():1320] Wrapping output streams.
2021-03-10 18:42:16,202 INFO    Thread-26 :3616 [wandb_run.py:_redirect():1336] Redirects installed.
2021-03-10 18:42:16,203 INFO    Thread-26 :3616 [wandb_init.py:init():527] run started, returning control to user process
2021-03-10 18:42:16,577 INFO    Thread-26 :3616 [wandb_setup.py:_flush():69] setting env: {'entity': '-my', 'project': 'dl_assignment1', 'root_dir': 'D:\\IITM\\deepLearning\\Assignments\\assignment1', 'sweep_id': '00phcm50', 'run_id': 'tncnr4za', 'sweep_param_path': 'D:\\IITM\\deepLearning\\Assignments\\assignment1\\wandb\\sweep-00phcm50\\config-tncnr4za.yaml'}
2021-03-10 18:42:16,580 INFO    Thread-26 :3616 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-10 18:42:16,584 INFO    Thread-26 :3616 [wandb_init.py:_log_setup():319] Logging user logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210310_184216-tncnr4za\logs\debug.log
2021-03-10 18:42:16,588 INFO    Thread-26 :3616 [wandb_init.py:_log_setup():320] Logging internal logs to D:\IITM\deepLearning\Assignments\assignment1\wandb\run-20210310_184216-tncnr4za\logs\debug-internal.log
2021-03-10 18:42:16,591 INFO    Thread-26 :3616 [wandb_init.py:init():352] calling init triggers
2021-03-10 18:42:16,594 INFO    Thread-26 :3616 [wandb_init.py:init():359] wandb.init called with sweep_config: {'alpha': 0, 'batch_size': 16, 'epochs': 10, 'hidden_Layer_AF': 'sigmoid', 'initializer': 'xavier', 'learning_rate': 0.001, 'loss_func': 'crossentropy', 'n_hidden_layers': 4, 'optimizer': 'nadam', 'size_hidden_layers': 64}
config: {}
2021-03-10 18:42:16,600 INFO    Thread-26 :3616 [wandb_init.py:init():398] wandb.init() called when a run is still active
